"addi %[others_cnt], %[others_cnt], 1\n\t"
   "mv t0, %[N]                            \n\t"
"addi %[others_cnt], %[others_cnt], 1\n\t"
        "mv t1, x0                              \n\t"
    "loop:                                      \n\t"
"addi %[others_cnt], %[others_cnt], 1\n\t"
        "srli t0, t0, 1                         \n\t"
"addi %[others_cnt], %[others_cnt], 1\n\t"
        "beqz t0, end_loop                      \n\t"
"addi %[add_cnt], %[add_cnt], 1\n\t"
        "addi t1, t1, 1                         \n\t"
"addi %[others_cnt], %[others_cnt], 1\n\t"
        "j loop                                 \n\t"
    "end_loop:                                  \n\t"
"addi %[others_cnt], %[others_cnt], 1\n\t"
        "mv %[log], t1                          \n\t"
